version: 2
registries:
  github-npm:
    type: npm-registry
    url: https://npm.pkg.github.com
    username: x-access-token
    # Store a Personal Access Token with read:packages scope as a Dependabot secret named GITHUB_PACKAGES_TOKEN
    # Settings > Secrets and variables > Dependabot > New repository secret
    password: ${{secrets.GITHUB_PACKAGES_TOKEN}}
updates:
  - package-ecosystem: "npm"
    directory: "/"
    registries:
      - github-npm
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
